language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable

before_script:
  - cp .env.travis .env
  - mysql -e 'create database smartsettia_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan migrate
  - php artisan db:seed
  - vendor/bin/phpunit

after_script:
  - ls -laR storage
  - cat storage/logs/*

notifications:
  slack: uidaho:KlprSysDjxzbBTJjtLAJZDks
